#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace budzet_domowy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baza_danych")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertforma_platnosci(forma_platnosci instance);
    partial void Updateforma_platnosci(forma_platnosci instance);
    partial void Deleteforma_platnosci(forma_platnosci instance);
    partial void Insertkategoria(kategoria instance);
    partial void Updatekategoria(kategoria instance);
    partial void Deletekategoria(kategoria instance);
    partial void Insertuzytkownicy(uzytkownicy instance);
    partial void Updateuzytkownicy(uzytkownicy instance);
    partial void Deleteuzytkownicy(uzytkownicy instance);
    partial void Insertoperacje(operacje instance);
    partial void Updateoperacje(operacje instance);
    partial void Deleteoperacje(operacje instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::budzet_domowy.Properties.Settings.Default.baza_danychConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<forma_platnosci> forma_platnosci
		{
			get
			{
				return this.GetTable<forma_platnosci>();
			}
		}
		
		public System.Data.Linq.Table<kategoria> kategoria
		{
			get
			{
				return this.GetTable<kategoria>();
			}
		}
		
		public System.Data.Linq.Table<uzytkownicy> uzytkownicy
		{
			get
			{
				return this.GetTable<uzytkownicy>();
			}
		}
		
		public System.Data.Linq.Table<operacje> operacje
		{
			get
			{
				return this.GetTable<operacje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.forma_platnosci")]
	public partial class forma_platnosci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_forma_platnosci;
		
		private string _nazwa;
		
		private EntitySet<operacje> _operacje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_forma_platnosciChanging(int value);
    partial void Onid_forma_platnosciChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    #endregion
		
		public forma_platnosci()
		{
			this._operacje = new EntitySet<operacje>(new Action<operacje>(this.attach_operacje), new Action<operacje>(this.detach_operacje));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_forma_platnosci", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_forma_platnosci
		{
			get
			{
				return this._id_forma_platnosci;
			}
			set
			{
				if ((this._id_forma_platnosci != value))
				{
					this.Onid_forma_platnosciChanging(value);
					this.SendPropertyChanging();
					this._id_forma_platnosci = value;
					this.SendPropertyChanged("id_forma_platnosci");
					this.Onid_forma_platnosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="forma_platnosci_operacje", Storage="_operacje", ThisKey="id_forma_platnosci", OtherKey="id_forma_platnosci")]
		public EntitySet<operacje> operacje
		{
			get
			{
				return this._operacje;
			}
			set
			{
				this._operacje.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.forma_platnosci = this;
		}
		
		private void detach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.forma_platnosci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoria")]
	public partial class kategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kategoria;
		
		private string _nazwa;
		
		private System.Nullable<int> _id_podkategoria;
		
		private string _typ;
		
		private EntitySet<kategoria> _kategoria2;
		
		private EntitySet<operacje> _operacje;
		
		private EntityRef<kategoria> _kategoria1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_kategoriaChanging(int value);
    partial void Onid_kategoriaChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void Onid_podkategoriaChanging(System.Nullable<int> value);
    partial void Onid_podkategoriaChanged();
    partial void OntypChanging(string value);
    partial void OntypChanged();
    #endregion
		
		public kategoria()
		{
			this._kategoria2 = new EntitySet<kategoria>(new Action<kategoria>(this.attach_kategoria2), new Action<kategoria>(this.detach_kategoria2));
			this._operacje = new EntitySet<operacje>(new Action<operacje>(this.attach_operacje), new Action<operacje>(this.detach_operacje));
			this._kategoria1 = default(EntityRef<kategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kategoria
		{
			get
			{
				return this._id_kategoria;
			}
			set
			{
				if ((this._id_kategoria != value))
				{
					this.Onid_kategoriaChanging(value);
					this.SendPropertyChanging();
					this._id_kategoria = value;
					this.SendPropertyChanged("id_kategoria");
					this.Onid_kategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_podkategoria", DbType="Int")]
		public System.Nullable<int> id_podkategoria
		{
			get
			{
				return this._id_podkategoria;
			}
			set
			{
				if ((this._id_podkategoria != value))
				{
					if (this._kategoria1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_podkategoriaChanging(value);
					this.SendPropertyChanging();
					this._id_podkategoria = value;
					this.SendPropertyChanged("id_podkategoria");
					this.Onid_podkategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="VarChar(50)")]
		public string typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this.OntypChanging(value);
					this.SendPropertyChanging();
					this._typ = value;
					this.SendPropertyChanged("typ");
					this.OntypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoria_kategoria", Storage="_kategoria2", ThisKey="id_kategoria", OtherKey="id_podkategoria")]
		public EntitySet<kategoria> kategoria2
		{
			get
			{
				return this._kategoria2;
			}
			set
			{
				this._kategoria2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoria_operacje", Storage="_operacje", ThisKey="id_kategoria", OtherKey="id_kategoria")]
		public EntitySet<operacje> operacje
		{
			get
			{
				return this._operacje;
			}
			set
			{
				this._operacje.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoria_kategoria", Storage="_kategoria1", ThisKey="id_podkategoria", OtherKey="id_kategoria", IsForeignKey=true)]
		public kategoria kategoria1
		{
			get
			{
				return this._kategoria1.Entity;
			}
			set
			{
				kategoria previousValue = this._kategoria1.Entity;
				if (((previousValue != value) 
							|| (this._kategoria1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoria1.Entity = null;
						previousValue.kategoria2.Remove(this);
					}
					this._kategoria1.Entity = value;
					if ((value != null))
					{
						value.kategoria2.Add(this);
						this._id_podkategoria = value.id_kategoria;
					}
					else
					{
						this._id_podkategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("kategoria1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kategoria2(kategoria entity)
		{
			this.SendPropertyChanging();
			entity.kategoria1 = this;
		}
		
		private void detach_kategoria2(kategoria entity)
		{
			this.SendPropertyChanging();
			entity.kategoria1 = null;
		}
		
		private void attach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.kategoria = this;
		}
		
		private void detach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.kategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uzytkownicy")]
	public partial class uzytkownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_uzytkownika;
		
		private string _imie;
		
		private string _nazwisko;
		
		private EntitySet<operacje> _operacje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_uzytkownikaChanging(int value);
    partial void Onid_uzytkownikaChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    #endregion
		
		public uzytkownicy()
		{
			this._operacje = new EntitySet<operacje>(new Action<operacje>(this.attach_operacje), new Action<operacje>(this.detach_operacje));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uzytkownika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_uzytkownika
		{
			get
			{
				return this._id_uzytkownika;
			}
			set
			{
				if ((this._id_uzytkownika != value))
				{
					this.Onid_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._id_uzytkownika = value;
					this.SendPropertyChanged("id_uzytkownika");
					this.Onid_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_operacje", Storage="_operacje", ThisKey="id_uzytkownika", OtherKey="id_uzytkownika")]
		public EntitySet<operacje> operacje
		{
			get
			{
				return this._operacje;
			}
			set
			{
				this._operacje.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = this;
		}
		
		private void detach_operacje(operacje entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.operacje")]
	public partial class operacje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_operacji;
		
		private System.DateTime _data;
		
		private decimal _kwota;
		
		private int _id_kategoria;
		
		private int _id_uzytkownika;
		
		private System.Nullable<int> _id_forma_platnosci;
		
		private string _opis;
		
		private EntityRef<forma_platnosci> _forma_platnosci;
		
		private EntityRef<kategoria> _kategoria;
		
		private EntityRef<uzytkownicy> _uzytkownicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_operacjiChanging(int value);
    partial void Onid_operacjiChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OnkwotaChanging(decimal value);
    partial void OnkwotaChanged();
    partial void Onid_kategoriaChanging(int value);
    partial void Onid_kategoriaChanged();
    partial void Onid_uzytkownikaChanging(int value);
    partial void Onid_uzytkownikaChanged();
    partial void Onid_forma_platnosciChanging(System.Nullable<int> value);
    partial void Onid_forma_platnosciChanged();
    partial void OnopisChanging(string value);
    partial void OnopisChanged();
    #endregion
		
		public operacje()
		{
			this._forma_platnosci = default(EntityRef<forma_platnosci>);
			this._kategoria = default(EntityRef<kategoria>);
			this._uzytkownicy = default(EntityRef<uzytkownicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_operacji", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_operacji
		{
			get
			{
				return this._id_operacji;
			}
			set
			{
				if ((this._id_operacji != value))
				{
					this.Onid_operacjiChanging(value);
					this.SendPropertyChanging();
					this._id_operacji = value;
					this.SendPropertyChanged("id_operacji");
					this.Onid_operacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwota", DbType="Decimal(10,2) NOT NULL")]
		public decimal kwota
		{
			get
			{
				return this._kwota;
			}
			set
			{
				if ((this._kwota != value))
				{
					this.OnkwotaChanging(value);
					this.SendPropertyChanging();
					this._kwota = value;
					this.SendPropertyChanged("kwota");
					this.OnkwotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategoria", DbType="Int NOT NULL")]
		public int id_kategoria
		{
			get
			{
				return this._id_kategoria;
			}
			set
			{
				if ((this._id_kategoria != value))
				{
					if (this._kategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_kategoriaChanging(value);
					this.SendPropertyChanging();
					this._id_kategoria = value;
					this.SendPropertyChanged("id_kategoria");
					this.Onid_kategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uzytkownika", DbType="Int NOT NULL")]
		public int id_uzytkownika
		{
			get
			{
				return this._id_uzytkownika;
			}
			set
			{
				if ((this._id_uzytkownika != value))
				{
					if (this._uzytkownicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._id_uzytkownika = value;
					this.SendPropertyChanged("id_uzytkownika");
					this.Onid_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_forma_platnosci", DbType="Int")]
		public System.Nullable<int> id_forma_platnosci
		{
			get
			{
				return this._id_forma_platnosci;
			}
			set
			{
				if ((this._id_forma_platnosci != value))
				{
					if (this._forma_platnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_forma_platnosciChanging(value);
					this.SendPropertyChanging();
					this._id_forma_platnosci = value;
					this.SendPropertyChanged("id_forma_platnosci");
					this.Onid_forma_platnosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="VarChar(200)")]
		public string opis
		{
			get
			{
				return this._opis;
			}
			set
			{
				if ((this._opis != value))
				{
					this.OnopisChanging(value);
					this.SendPropertyChanging();
					this._opis = value;
					this.SendPropertyChanged("opis");
					this.OnopisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="forma_platnosci_operacje", Storage="_forma_platnosci", ThisKey="id_forma_platnosci", OtherKey="id_forma_platnosci", IsForeignKey=true)]
		public forma_platnosci forma_platnosci
		{
			get
			{
				return this._forma_platnosci.Entity;
			}
			set
			{
				forma_platnosci previousValue = this._forma_platnosci.Entity;
				if (((previousValue != value) 
							|| (this._forma_platnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._forma_platnosci.Entity = null;
						previousValue.operacje.Remove(this);
					}
					this._forma_platnosci.Entity = value;
					if ((value != null))
					{
						value.operacje.Add(this);
						this._id_forma_platnosci = value.id_forma_platnosci;
					}
					else
					{
						this._id_forma_platnosci = default(Nullable<int>);
					}
					this.SendPropertyChanged("forma_platnosci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoria_operacje", Storage="_kategoria", ThisKey="id_kategoria", OtherKey="id_kategoria", IsForeignKey=true)]
		public kategoria kategoria
		{
			get
			{
				return this._kategoria.Entity;
			}
			set
			{
				kategoria previousValue = this._kategoria.Entity;
				if (((previousValue != value) 
							|| (this._kategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoria.Entity = null;
						previousValue.operacje.Remove(this);
					}
					this._kategoria.Entity = value;
					if ((value != null))
					{
						value.operacje.Add(this);
						this._id_kategoria = value.id_kategoria;
					}
					else
					{
						this._id_kategoria = default(int);
					}
					this.SendPropertyChanged("kategoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_operacje", Storage="_uzytkownicy", ThisKey="id_uzytkownika", OtherKey="id_uzytkownika", IsForeignKey=true)]
		public uzytkownicy uzytkownicy
		{
			get
			{
				return this._uzytkownicy.Entity;
			}
			set
			{
				uzytkownicy previousValue = this._uzytkownicy.Entity;
				if (((previousValue != value) 
							|| (this._uzytkownicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._uzytkownicy.Entity = null;
						previousValue.operacje.Remove(this);
					}
					this._uzytkownicy.Entity = value;
					if ((value != null))
					{
						value.operacje.Add(this);
						this._id_uzytkownika = value.id_uzytkownika;
					}
					else
					{
						this._id_uzytkownika = default(int);
					}
					this.SendPropertyChanged("uzytkownicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
